name: Main
on: [push]
env:
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
  TF_IN_AUTOMATION: true
  TF_INPUT: true
jobs:
  main:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform
    steps:
      - uses: actions/checkout@v2
      - name: Lint
        run: terraform fmt -recursive -check
      - name: Initialize
        run: terraform init test -backend-config "${GITHUB_REPOSITORY}-${GITHUB_REF}"
      - name: Apply
        run: terraform apply -auto-approve test
        continue-on-error: true # ensure that ephemeral environment is destroyed
      - name: Apply Idempotency Check
        run: terraform plan -detailed-exitcode test
        continue-on-error: true # ensure that ephemeral environment is destroyed
      - name: Destroy
        run: terraform destroy -auto-approve test
      - name: Destroy Idempotency Check
        run: terraform plan -detailed-exitcode -destroy test
